language: csharp
mono: none
dotnet: 2.1.505
sudo: false
env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - cd BugCheck
  - dotnet restore
  - dotnet build BugCheckSystem.sln -c Release
